version: "3.7"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./migration/data:/var/lib/postgresql/data
      - ./migration/sql:/docker-entrypoint-initdb.d